# OMPL planning configuration for DOFBOT Pro
planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.0  # Max step size

  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    range: 0.0  # Max step size
    border_fraction: 0.9
    min_valid_path_fraction: 0.5

  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0  # Max step size

  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0  # Max step size

  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0  # Max step size
    goal_bias: 0.05
    delay_collision_checking: 1

  TRRTkConfigDefault:
    type: geometric::TRRT
    range: 0.0  # Max step size
    goal_bias: 0.05
    max_states_failed: 10
    temp_change_factor: 2.0
    min_temperature: 10e-10
    init_temperature: 10e-6
    frountier_threshold: 0.0
    frountierNodeRatio: 0.1
    k_constant: 0.0

  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10

  PRMstarkConfigDefault:
    type: geometric::PRMstar

# Planning groups configuration
arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(joint1,joint2)
  longest_valid_segment_fraction: 0.01

gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
  longest_valid_segment_fraction: 0.01