controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      joint1:
        trajectory: 0.1
        goal: 0.05
      joint2:
        trajectory: 0.1
        goal: 0.05
      joint3:
        trajectory: 0.1
        goal: 0.05
      joint4:
        trajectory: 0.1
        goal: 0.05
      joint5:
        trajectory: 0.1
        goal: 0.05
      joint6:
        trajectory: 0.1
        goal: 0.05

joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6