# ROS-Gazebo桥接配置
# 定义ROS2话题和Gazebo话题之间的映射关系

# 机械臂关节状态
- ros_topic_name: "/dofbot_pro/joint_states"
  gz_topic_name: "/dofbot_pro/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# 机械臂关节命令
- ros_topic_name: "/dofbot_pro/joint_trajectory_controller/joint_trajectory"
  gz_topic_name: "/dofbot_pro/joint_trajectory"
  ros_type_name: "trajectory_msgs/msg/JointTrajectory"
  gz_type_name: "gz.msgs.JointTrajectory"
  direction: ROS_TO_GZ

# 相机RGB图像
- ros_topic_name: "/camera/rgb/image_raw"
  gz_topic_name: "/camera/rgb/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# 相机深度图像
- ros_topic_name: "/camera/depth/image_raw"
  gz_topic_name: "/camera/depth/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# 相机信息
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# 时钟同步
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# TF变换
- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# 世界模型状态
- ros_topic_name: "/world/chess_world/model/state"
  gz_topic_name: "/world/chess_world/model/state"
  ros_type_name: "ros_gz_interfaces/msg/EntityState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS